VERSION 5.00
Object = "{00028C01-0000-0000-0000-000000000046}#1.0#0"; "DBGRID32.OCX"
Object = "{00025600-0000-0000-C000-000000000046}#4.6#0"; "CRYSTL32.OCX"
Object = "{C932BA88-4374-101B-A56C-00AA003668DC}#1.1#0"; "MSMASK32.OCX"
Begin VB.Form PrgSolicitud 
   AutoRedraw      =   -1  'True
   Caption         =   "Ingresos de  Solicitud  de O.P"
   ClientHeight    =   6750
   ClientLeft      =   60
   ClientTop       =   1155
   ClientWidth     =   11880
   ForeColor       =   &H00FFFFFF&
   LinkTopic       =   "Form2"
   ScaleHeight     =   6750
   ScaleWidth      =   11880
   Begin VB.CommandButton Limpia1 
      Caption         =   "Limpia Renglon"
      Height          =   300
      Left            =   2040
      TabIndex        =   39
      Top             =   2640
      Width           =   1695
   End
   Begin VB.TextBox Ayuda 
      BeginProperty Font 
         Name            =   "MS Sans Serif"
         Size            =   9.75
         Charset         =   0
         Weight          =   400
         Underline       =   0   'False
         Italic          =   0   'False
         Strikethrough   =   0   'False
      EndProperty
      Height          =   285
      Left            =   7200
      TabIndex        =   38
      Top             =   120
      Visible         =   0   'False
      Width           =   4575
   End
   Begin VB.CommandButton calcret 
      Caption         =   "Calc.Ret."
      Height          =   300
      Left            =   4920
      TabIndex        =   37
      Top             =   2640
      Visible         =   0   'False
      Width           =   975
   End
   Begin VB.TextBox Retencion 
      Alignment       =   1  'Right Justify
      Height          =   285
      Left            =   4920
      TabIndex        =   36
      Text            =   " "
      Top             =   1560
      Width           =   975
   End
   Begin VB.TextBox Banco 
      Alignment       =   1  'Right Justify
      Height          =   285
      Left            =   1680
      TabIndex        =   33
      Text            =   " "
      Top             =   1080
      Width           =   735
   End
   Begin VB.Frame IngreCuenta 
      Caption         =   "Cuenta Contable"
      Height          =   855
      Left            =   2880
      TabIndex        =   27
      Top             =   3360
      Visible         =   0   'False
      Width           =   3855
      Begin VB.TextBox Cuenta 
         Height          =   285
         Left            =   1560
         TabIndex        =   29
         Text            =   " "
         Top             =   360
         Width           =   1695
      End
      Begin VB.Label Label4 
         Caption         =   "Codigo"
         Height          =   255
         Left            =   360
         TabIndex        =   28
         Top             =   360
         Width           =   1215
      End
   End
   Begin VB.TextBox Observaciones 
      Height          =   285
      Left            =   1680
      TabIndex        =   25
      Text            =   " "
      Top             =   720
      Width           =   5415
   End
   Begin VB.CommandButton Impresion 
      Caption         =   "Impresion"
      Height          =   300
      Left            =   3840
      TabIndex        =   23
      Top             =   2640
      Width           =   975
   End
   Begin Crystal.CrystalReport LISTADO 
      Left            =   6000
      Top             =   120
      _ExtentX        =   741
      _ExtentY        =   741
      _Version        =   262150
      ReportFileName  =   "ordpago.rpt"
      WindowTitle     =   "Orden de Pago"
      CopiesToPrinter =   2
      WindowState     =   2
   End
   Begin VB.Frame Frame1 
      Caption         =   "Tipo de Orden de Pago"
      Height          =   1095
      Left            =   0
      TabIndex        =   16
      Top             =   1440
      Width           =   3735
      Begin VB.OptionButton Tipo5 
         Caption         =   "Cheques Rechazados"
         Height          =   255
         Left            =   120
         TabIndex        =   31
         Top             =   720
         Width           =   2055
      End
      Begin VB.OptionButton Tipo4 
         Caption         =   "Transferencias"
         Height          =   255
         Left            =   2040
         TabIndex        =   30
         Top             =   480
         Width           =   1575
      End
      Begin VB.OptionButton Tipo3 
         Caption         =   "Pagos Varios"
         Height          =   255
         Left            =   120
         TabIndex        =   26
         Top             =   480
         Width           =   1695
      End
      Begin VB.OptionButton Tipo1 
         Caption         =   "Pagos de Cta.Cte."
         Height          =   255
         Left            =   120
         TabIndex        =   18
         Top             =   240
         Width           =   1815
      End
      Begin VB.OptionButton Tipo2 
         Caption         =   "Anticipos"
         Height          =   255
         Left            =   2040
         TabIndex        =   17
         Top             =   240
         Width           =   1335
      End
   End
   Begin VB.TextBox Proveedor 
      Alignment       =   1  'Right Justify
      Height          =   285
      Left            =   1680
      MaxLength       =   11
      TabIndex        =   2
      Text            =   " "
      Top             =   360
      Width           =   1335
   End
   Begin VB.ListBox Opcion 
      BeginProperty Font 
         Name            =   "MS Sans Serif"
         Size            =   9.75
         Charset         =   0
         Weight          =   700
         Underline       =   0   'False
         Italic          =   0   'False
         Strikethrough   =   0   'False
      EndProperty
      Height          =   1980
      Left            =   7200
      TabIndex        =   14
      Top             =   480
      Visible         =   0   'False
      Width           =   3975
   End
   Begin MSMask.MaskEdBox Fecha 
      Height          =   285
      Left            =   3240
      TabIndex        =   1
      Top             =   0
      Width           =   1215
      _ExtentX        =   2143
      _ExtentY        =   503
      _Version        =   327680
      MaxLength       =   10
      Mask            =   "##/##/####"
      PromptChar      =   " "
   End
   Begin MSDBGrid.DBGrid DbGrid1 
      Height          =   3015
      Left            =   0
      OleObjectBlob   =   "Solicitud.frx":0000
      TabIndex        =   3
      Top             =   3000
      Width           =   11775
   End
   Begin VB.TextBox Orden 
      Alignment       =   1  'Right Justify
      Height          =   285
      Left            =   1680
      MaxLength       =   6
      TabIndex        =   0
      Text            =   " "
      Top             =   0
      Width           =   735
   End
   Begin VB.ListBox WIndice 
      Height          =   255
      Left            =   5640
      TabIndex        =   12
      Top             =   120
      Visible         =   0   'False
      Width           =   975
   End
   Begin VB.ListBox Pantalla 
      BeginProperty Font 
         Name            =   "MS Sans Serif"
         Size            =   9.75
         Charset         =   0
         Weight          =   400
         Underline       =   0   'False
         Italic          =   0   'False
         Strikethrough   =   0   'False
      EndProperty
      Height          =   2460
      ItemData        =   "Solicitud.frx":09C2
      Left            =   7200
      List            =   "Solicitud.frx":09C9
      TabIndex        =   11
      Top             =   480
      Visible         =   0   'False
      Width           =   4575
   End
   Begin VB.CommandButton Consulta 
      Caption         =   "Consulta"
      Height          =   300
      Left            =   4920
      TabIndex        =   10
      Top             =   2280
      Width           =   975
   End
   Begin VB.CommandButton CmdLimpiar 
      Caption         =   "Limpiar"
      Height          =   300
      Left            =   3840
      TabIndex        =   4
      Top             =   2280
      Width           =   975
   End
   Begin VB.CommandButton cmdClose 
      Caption         =   "&Cerrar"
      Height          =   300
      Left            =   4920
      TabIndex        =   9
      Top             =   1920
      Width           =   975
   End
   Begin VB.CommandButton cmdDelete 
      Caption         =   "&Eliminar"
      Height          =   300
      Left            =   240
      TabIndex        =   8
      Top             =   2640
      Visible         =   0   'False
      Width           =   975
   End
   Begin VB.CommandButton cmdAdd 
      Caption         =   "&Grabar"
      Height          =   300
      Left            =   3840
      TabIndex        =   7
      Top             =   1920
      Width           =   975
   End
   Begin VB.Label Label6 
      BorderStyle     =   1  'Fixed Single
      Caption         =   "Retencion"
      Height          =   255
      Left            =   3840
      TabIndex        =   35
      Top             =   1560
      Width           =   975
   End
   Begin VB.Label DesBanco 
      BorderStyle     =   1  'Fixed Single
      Caption         =   " "
      Height          =   255
      Left            =   2520
      TabIndex        =   34
      Top             =   1080
      Width           =   4575
   End
   Begin VB.Label bjm 
      Caption         =   "Banco"
      Height          =   255
      Left            =   120
      TabIndex        =   32
      Top             =   1080
      Width           =   1575
   End
   Begin VB.Label Label3 
      Caption         =   "Observaciones"
      Height          =   255
      Left            =   120
      TabIndex        =   24
      Top             =   720
      Width           =   1455
   End
   Begin VB.Label Label2 
      Caption         =   "Proveedor"
      Height          =   255
      Left            =   120
      TabIndex        =   22
      Top             =   360
      Width           =   1455
   End
   Begin VB.Label Creditos 
      Alignment       =   1  'Right Justify
      BorderStyle     =   1  'Fixed Single
      Caption         =   " "
      Height          =   255
      Left            =   9960
      TabIndex        =   21
      Top             =   6120
      Width           =   1215
   End
   Begin VB.Label Debitos 
      Alignment       =   1  'Right Justify
      BorderStyle     =   1  'Fixed Single
      Caption         =   " "
      Height          =   255
      Left            =   2760
      TabIndex        =   20
      Top             =   6120
      Width           =   1215
   End
   Begin VB.Label Label5 
      BorderStyle     =   1  'Fixed Single
      Caption         =   "Tipo de Doc. : 1) Ef.   2) Bco.  3) Ch. Terc.  4) Documentos"
      Height          =   255
      Left            =   5640
      TabIndex        =   19
      Top             =   6120
      Width           =   4335
   End
   Begin VB.Label DesProveedor 
      BorderStyle     =   1  'Fixed Single
      Caption         =   " "
      Height          =   285
      Left            =   3120
      TabIndex        =   15
      Top             =   360
      Width           =   2295
   End
   Begin VB.Label Label1 
      Caption         =   "Fecha"
      Height          =   375
      Left            =   2520
      TabIndex        =   13
      Top             =   0
      Width           =   975
   End
   Begin VB.Label lblLabels 
      Caption         =   " "
      Height          =   255
      Index           =   1
      Left            =   120
      TabIndex        =   6
      Top             =   360
      Width           =   1455
   End
   Begin VB.Label lblLabels 
      Caption         =   "Nro Solicitud"
      Height          =   255
      Index           =   0
      Left            =   120
      TabIndex        =   5
      Top             =   60
      Width           =   1575
   End
End
Attribute VB_Name = "PrgSolicitud"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Private mTotalRows& ' Contiene las filas totales del conjunto de registros
Private UserData() As Variant ' Matriz de 2 dimensiones que contiene registros
Private Const MAXCOLS = 12  ' Número máximo de campos del conjunto de registros.
Private Debito As Double
Private Credito As Double
Private WImpresion(12, 10) As String
Private WImpre2(12, 10) As String
Private WDebito(12, 2) As String
Private WCredito(12, 4) As String
Private WCuenta(12) As String
Private WCuentaBco As String
Private Numero As String
Private WNumero As String
Private WSaldo As Double
Private WRetencion As Double
Private WCuatri  As String
Private WEmpNombre As String
Private WEmpDirecion As String
Private WEmpLocalidad As String
Private WEmpCuit As String
Private WPrvDireccion As String
Private WPrvCuit As String
Private WLeyenda(10) As String
Private WTipo As String
Private WTipoprv As Single
Private WTipoiva As Single
Private WNeto As Double
Private WAnticipo As Double
Private WBruto As Double
Private WIva As Double
Private WRetenido As Double
Private WFecha As String
Private XNeto As Double
Private XBruto As Double
Private XIva As Double
Private XTBase As Double
Private XImpor As Double
Private WParametro(0 To 10) As Double
Private WTasa1(10) As Double
Private WAuxi As Double
Private Total As Double
Private Auxi As String

Private Sub Suma_Datos()
    Debitos.Caption = ""
    Creditos.Caption = ""
    
    For iRow = 0 To 9
        DbGrid1.Col = 4
        DbGrid1.Row = iRow
        If Val(DbGrid1.Text) <> 0 Then
            Debitos.Caption = Str$(Val(Debitos.Caption) + Val(DbGrid1.Text))
        End If
        DbGrid1.Col = 11
        DbGrid1.Row = iRow
        If Val(DbGrid1.Text) <> 0 Then
            Creditos.Caption = Str$(Val(Creditos.Caption) + Val(DbGrid1.Text))
        End If
    Next iRow
    
    If Existe <> "S" Then
        Call calcret_Click
    End If
    Creditos.Caption = Str$(Val(Creditos.Caption) + Val(Retencion.Text))
    
    Debitos.Caption = Pusing("###,###.##", Debitos.Caption)
    Creditos.Caption = Pusing("###,###.##", Creditos.Caption)
    DbGrid1.Col = 0
    DbGrid1.Row = 0
    
End Sub

Private Sub Lee_Datos()
    Renglon = 0
    Debito = 0
    Credito = 0
    Do
        With rstSolicitud
            .Index = "Clave"
            Renglon = Renglon + 1
            Auxi1 = Str$(Renglon)
            Call Ceros(Auxi1, 2)
            .Seek "=", Orden.Text + Auxi1
            If .NoMatch = False Then
                Select Case Val(!Tiporeg)
                    Case 1
                        Debito = Debito + 1
                        DbGrid1.Row = Debito - 1
                        DbGrid1.Col = 0
                        DbGrid1.Text = !Tipo1
                        DbGrid1.Col = 1
                        DbGrid1.Text = !Letra1
                        DbGrid1.Col = 2
                        DbGrid1.Text = !Punto1
                        DbGrid1.Col = 3
                        DbGrid1.Text = !Numero1
                        DbGrid1.Col = 4
                        DbGrid1.Text = !Importe1
                        DbGrid1.Text = Pusing("###,###.##", DbGrid1.Text)
                        DbGrid1.Col = 5
                        DbGrid1.Text = !Observaciones2
                    Case 2
                        Credito = Credito + 1
                        DbGrid1.Row = Credito - 1
                        DbGrid1.Col = 6
                        DbGrid1.Text = !Tipo2
                        DbGrid1.Col = 7
                        DbGrid1.Text = !Numero2
                        DbGrid1.Col = 8
                        DbGrid1.Text = !Fecha2
                        DbGrid1.Col = 9
                        DbGrid1.Text = !Banco2
                        DbGrid1.Col = 10
                        If !Observaciones2 <> "" Then
                            DbGrid1.Text = !Observaciones2
                        End If
                        DbGrid1.Col = 11
                        DbGrid1.Text = !Importe2
                        DbGrid1.Text = Pusing("###,###.##", DbGrid1.Text)
                    Case Else
                End Select
                    Else
                Exit Do
            End If
        End With
    Loop
End Sub

Sub Verifica_datos()
End Sub

Sub Format_datos()
    Rem Retganancias.text = PUsing("###,###.##", Retganancias.text)
End Sub

Sub Imprime_Datos()
    With rstProveedor
        .Index = "Proveedor"
        .Seek "=", Proveedor.Text
        If .NoMatch = False Then
            Proveedor.Text = !Proveedor
            DesProveedor.Caption = !Nombre
            WPrvDireccion = !Direccion
            WPrvCuit = !Cuit
            WTipoprv = Val(!Tipo) + 1
            WTipoiva = Val(!Iva)
            Call Format_datos
        End If
    End With
End Sub

Private Sub cmdAdd_Click()

    If Orden.Text <> "" And Fecha.Text <> "" Then
    
    If Proveedor.Text <> "" Or Tipo3.Value = True Or Tipo4.Value = True Or Tipo5.Value = True Then
    
    Auxi1 = Orden.Text
    Call Ceros(Auxi1, 6)
    Orden.Text = Auxi1
        
    With rstSolicitud
        Existe = "N"
        .Index = "Clave"
        Claveven$ = Orden.Text + "01"
        .Seek "=", Claveven$
        If .NoMatch = False Then
            Existe = "S"
        End If
    End With
    
    If Existe <> "S" Then
    
        Call Suma_Datos
        
        Debito = 0
        Credito = 0
        Rem If Val(Debitos.Caption) <> 0 Then
        Rem     Debito = Val(Debitos.Caption)
        Rem End If
        
        Rem If Val(Creditos.Caption) <> 0 Then
        Rem     Credito = Val(Creditos.Caption)
        Rem End If
        
        If Debito = Credito Then
        
        If Val(Proveedor.Text) = 0 Then
            Proveedor.Text = "0"
        End If
        If Val(Banco.Text) = 0 Then
            Banco.Text = "0"
        End If
    
        With rstSolicitud
            Renglon = 0
            .Index = "Clave"
            For iRow = 0 To 9
                WRow = iRow
                DbGrid1.Col = 4
                DbGrid1.Row = iRow
                If Val(DbGrid1.Text) <> 0 Then
                    .AddNew
                    Renglon = Renglon + 1
                    Auxi1 = Str$(Renglon)
                    Call Ceros(Auxi1, 2)
                    !Orden = Orden.Text
                    !Renglon = Auxi1
                    !Proveedor = Proveedor.Text
                    !Fecha = Fecha.Text
                    !FechaOrd = Right$(Fecha.Text, 4) + Mid$(Fecha.Text, 4, 2) + Left$(Fecha.Text, 2)
                    !Importe = Val(Debito)
                    !Retencion = Val(Retencion.Text)
                    !Observaciones = Observaciones.Text
                    !Cuenta = ""
                    If Tipo1.Value = True Then
                        !TipoOrd = "1"
                    End If
                    If Tipo2.Value = True Then
                        !TipoOrd = "2"
                    End If
                    If Tipo3.Value = True Then
                        !TipoOrd = "3"
                        !Cuenta = WCuenta(iRow)
                    End If
                    If Tipo4.Value = True Then
                        !TipoOrd = "4"
                        !Cuenta = WCuenta(iRow)
                    End If
                    If Tipo5.Value = True Then
                        !TipoOrd = "5"
                        !Cuenta = WCuenta(iRow)
                    End If
                    
                    !Tiporeg = "1"
                    DbGrid1.Col = 0
                    !Tipo1 = Left$(DbGrid1.Text, 2)
                    DbGrid1.Col = 1
                    !Letra1 = Left$(DbGrid1.Text, 1)
                    DbGrid1.Col = 2
                    !Punto1 = Left$(DbGrid1.Text, 4)
                    DbGrid1.Col = 3
                    !Numero1 = Left$(DbGrid1.Text, 8)
                    DbGrid1.Col = 4
                    !Importe1 = Val(DbGrid1.Text)
                    DbGrid1.Col = 5
                    !Observaciones2 = Left$(DbGrid1.Text, 30)
                    !Tipo2 = ""
                    !Numero2 = ""
                    !Fecha2 = ""
                    !FechaOrd2 = ""
                    If Tipo4.Value = True Then
                        !Banco2 = Val(Banco.Text)
                            Else
                        !Banco2 = 0
                    End If
                    !Importe2 = 0
                    !Clave = !Orden + !Renglon
                    .Update
                    .Bookmark = .LastModified
                    
                    WLetra = !Letra1
                    WTipo = !Tipo1
                    WPunto = !Punto1
                    WNumero = !Numero1
                    WIMporte = !Importe1
                    
                    If Tipo1.Value = True Then
                        With rstCtaCtePrv
                            .Index = "CtaCte"
                            Claveven$ = Proveedor.Text + WLetra + WTipo + WPunto + WNumero
                            .Seek "=", Claveven$
                            If .NoMatch = False Then
                                .Edit
                                !Saldo = !Saldo - WIMporte
                                .Update
                            End If
                        End With
                    End If
                    
                End If
                
                DbGrid1.Col = 11
                DbGrid1.Row = iRow
                If Val(DbGrid1.Text) <> 0 Then
                    .AddNew
                    Renglon = Renglon + 1
                    Auxi1 = Str$(Renglon)
                    Call Ceros(Auxi1, 2)
                    !Orden = Orden.Text
                    !Renglon = Auxi1
                    !Proveedor = Proveedor.Text
                    !Fecha = Fecha.Text
                    !FechaOrd = Right$(Fecha.Text, 4) + Mid$(Fecha.Text, 4, 2) + Left$(Fecha.Text, 2)
                    !Importe = Val(Debito)
                    !Retencion = Val(Retencion.Text)
                    !Observaciones = Observaciones.Text
                    If Tipo1.Value = True Then
                        !TipoOrd = "1"
                    End If
                    If Tipo2.Value = True Then
                        !TipoOrd = "2"
                    End If
                    If Tipo3.Value = True Then
                        !TipoOrd = "3"
                    End If
                    If Tipo4.Value = True Then
                        !TipoOrd = "4"
                    End If
                    If Tipo5.Value = True Then
                        !TipoOrd = "5"
                    End If
                    !Tiporeg = "2"
                    !Tipo1 = ""
                    !Letra1 = ""
                    !Punto1 = ""
                    !Numero1 = ""
                    !Importe1 = 0
                    DbGrid1.Col = 6
                    !Tipo2 = Left$(DbGrid1.Text, 2)
                    DbGrid1.Col = 7
                    !Numero2 = Left$(DbGrid1.Text, 8)
                    DbGrid1.Col = 8
                    !Fecha2 = Left$(DbGrid1.Text, 10)
                    !FechaOrd2 = Right$(!Fecha2, 4) + Mid$(!Fecha2, 4, 2) + Left$(!Fecha2, 2)
                    DbGrid1.Col = 9
                    !Banco2 = Val(DbGrid1.Text)
                    DbGrid1.Col = 10
                    !Observaciones2 = Left$(DbGrid1.Text, 20)
                    DbGrid1.Col = 11
                    !Importe2 = Val(DbGrid1.Text)
                    !Clave = !Orden + !Renglon
                    .Update
                    .Bookmark = .LastModified
                    
                    Rem dada
                    
                    If !Tipo2 = 3 Then
                        With rstRecibos
                            .Index = "Clave"
                            DbGrid1.Col = 12
                            Claveven$ = DbGrid1.Text
                            .Seek "=", Claveven$
                            If .NoMatch = False Then
                                .Edit
                                !Estado2 = "X"
                                Rem !Destino = DesProveedor.Caption
                                .Update
                            End If
                        End With
                    End If
                    
                    If !Tipo2 = 4 Then
                        With rstCtaCte
                            .Index = "Clave"
                            DbGrid1.Col = 12
                            Claveven$ = DbGrid1.Text
                            .Seek "=", Claveven$
                            If .NoMatch = False Then
                                .Edit
                                !Saldo = 0
                                !SaldoUs = 0
                                !Estado = "1"
                                .Update
                            End If
                        End With
                    End If
                    
                End If
                
            Next iRow
        End With
        
        With rstEmpresa
            .Index = "Empresa"
            Claveven$ = "1"
            .Seek "=", Claveven$
            If .NoMatch = False Then
                WCtaProveedor = !CtaProveedores
                WCtaEfectivo = !CtaEfectivo
                WCtaCheques = !CtaCheque
            End If
        End With
        
        Rem With rstImputac
        Rem     Renglon = 0
        Rem     .Index = "Clave"
        Rem
        Rem     For iRow = 0 To 9
        Rem         WRow = iRow
        Rem         DbGrid1.Col = 4
        Rem         DbGrid1.Row = iRow
        Rem         If Val(DbGrid1.Text) <> 0 Then
        Rem             .AddNew
        Rem             !Tipomovi = "3"
        Rem             !Proveedor = Proveedor.Text
        Rem             !TipoComp = "01"
        Rem             !LetraComp = "A"
        Rem             !PuntoComp = "0000"
        Rem             !NroComp = Orden.Text
        Rem             Renglon = Renglon + 1
        Rem             Auxi1 = Str$(Renglon)
        Rem             Call Ceros(Auxi1, 2)
        Rem             !Renglon = Auxi1$
        Rem             !Fecha = Fecha.Text
        Rem             !Observaciones = DesProveedor.Caption
        Rem             If Tipo1.Value = True Or Tipo2.Value = True Then
        Rem                 !Cuenta = WCtaProveedor
        Rem             End If
        Rem             If Tipo3.Value = True Then
        Rem                 !Cuenta = WCuenta(iRow)
        Rem             End If
        Rem              !Credito = 0
        Rem             !Debito = Val(DbGrid1.Text)
        Rem             !fechaord = Right$(Fecha.Text, 4) + Mid$(Fecha.Text, 4, 2) + Left$(Fecha.Text, 2)
        Rem             !Titulo = "Pagos"
        Rem             !Empresa = 1
        Rem             !Clave = !Tipomovi + !TipoComp + !LetraComp + !PuntoComp + !NroComp + !Renglon
        Rem             .Update
        Rem         End If
        Rem
        Rem         DbGrid1.Col = 11
        Rem         DbGrid1.Row = iRow
        Rem         If Val(DbGrid1.Text) <> 0 Then
        Rem             .AddNew
        Rem             !Tipomovi = "3"
        Rem             !Proveedor = Proveedor.Text
        Rem             !TipoComp = "01"
        Rem             !LetraComp = "A"
        Rem             !PuntoComp = "0000"
        Rem             !NroComp = Orden.Text
        Rem             Renglon = Renglon + 1
        Rem             Auxi1 = Str$(Renglon)
        Rem             Call Ceros(Auxi1, 2)
        Rem             !Renglon = Auxi1$
        Rem             !Fecha = Fecha.Text
        Rem             !Observaciones = DesProveedor.Caption
        Rem             !Credito = Val(DbGrid1.Text)
        Rem             !Debito = 0
        Rem             !fechaord = Right$(Fecha.Text, 4) + Mid$(Fecha.Text, 4, 2) + Left$(Fecha.Text, 2)
        Rem             !Titulo = "Pagos"
        Rem             !Empresa = 1
        Rem             DbGrid1.Col = 6
        Rem             Select Case Val(DbGrid1.Text)
        Rem                 Case 2
        Rem                     !Cuenta = "999999"
        Rem                     With rstBanco
        Rem                         DbGrid1.Col = 9
        Rem                         .Index = "Banco"
        Rem                         .Seek "=", Val(DbGrid1.Text)
        Rem                         If .NoMatch = False Then
        Rem                             xCuenta = !Cuenta
        Rem                         End If
        Rem                     End With
        Rem                     !Cuenta = xCuenta
        Rem                 Case 3
        Rem                     !Cuenta = WCtaCheques
        Rem                 Case Else
        Rem                     !Cuenta = WCtaEfectivo
        Rem             End Select
        Rem             !Clave = !Tipomovi + !TipoComp + !LetraComp + !PuntoComp + !NroComp + !Renglon
        Rem             .Update
        Rem         End If
        Rem
        Rem     Next iRow
        Rem End With
        
        If Tipo1.Value = True Then
        
            WLetra = "A"
            WTipo = "04"
            WPunto = "0000"
            WNumero = Orden.Text
            WProveedor = Proveedor.Text
        
            Call Ceros(WNumero, 8)
            Rem Call Ceros(WProveedor, 6)
        
            With rstCtaCtePrv
                .Index = "CtaCte"
                .Seek "=", WProveedor + WLetra + WTipo + WPunto + WNumero
                If .NoMatch Then
                    .AddNew
                    !Proveedor = Proveedor.Text
                    !Letra = WLetra
                    !Tipo = WTipo
                    !Punto = WPunto
                    !Numero = WNumero
                    !Fecha = Fecha.Text
                    !Estado = "1"
                    !Vencimiento = "  /  /    "
                    !Total = Debito * -1
                    !Saldo = 0
                    !Clave = WProveedor + WLetra + WTipo + WPunto + WNumero
                    !OrdFecha = Right$(Fecha.Text, 4) + Mid$(Fecha.Text, 4, 2) + Left$(Fecha.Text, 2)
                    !OrdVencimiento = "00000000"
                    !Impre = "OP"
                    .Update
                    .Bookmark = .LastModified
                        Else
                    .Edit
                    !Proveedor = Proveedor.Text
                    !Letra = WLetra
                    !Tipo = WTipo
                    !Punto = WPunto
                    !Numero = WNumero
                    !Fecha = Fecha.Text
                    !Estado = "1"
                    !Vencimiento = "  /  /    "
                    !Total = Debito * -1
                    !Saldo = 0
                    !Clave = WProveedor + WLetra + WTipo + WPunto + WNumero
                    !OrdFecha = Right$(Fecha.Text, 4) + Mid$(Fecha.Text, 4, 2) + Left$(Fecha.Text, 2)
                    !OrdVencimiento = "00000000"
                    !Impre = "OP"
                    .Update
                    .Bookmark = .LastModified
                End If
            End With
        End If
        Rem dada
        If Tipo2.Value = True Then
        
            WLetra = "A"
            WTipo = "05"
            WPunto = "0000"
            WNumero = Orden.Text
            WProveedor = Proveedor.Text
        
            Call Ceros(WNumero, 8)
            Rem Call Ceros(WProveedor, 6)
        
            With rstCtaCtePrv
                .Index = "CtaCte"
                .Seek "=", WProveedor + WLetra + WTipo + WPunto + WNumero
                If .NoMatch Then
                    .AddNew
                    !Proveedor = Proveedor.Text
                    !Letra = WLetra
                    !Tipo = WTipo
                    !Punto = WPunto
                    !Numero = WNumero
                    !Fecha = Fecha.Text
                    !Estado = "1"
                    !Vencimiento = "  /  /    "
                    !Total = Debito * -1
                    !Saldo = Debito * -1
                    !Clave = WProveedor + WLetra + WTipo + WPunto + WNumero
                    !OrdFecha = Right$(Fecha.Text, 4) + Mid$(Fecha.Text, 4, 2) + Left$(Fecha.Text, 2)
                    !OrdVencimiento = "00000000"
                    !Impre = "AN"
                    .Update
                    .Bookmark = .LastModified
                        Else
                    .Edit
                    !Proveedor = Proveedor.Text
                    !Letra = WLetra
                    !Tipo = WTipo
                    !Punto = WPunto
                    !Numero = WNumero
                    !Fecha = Fecha.Text
                    !Estado = "1"
                    !Vencimiento = "  /  /    "
                    !Total = Debito * -1
                    !Saldo = Debito * -1
                    !Clave = WProveedor + WLetra + WTipo + WPunto + WNumero
                    !OrdFecha = Right$(Fecha.Text, 4) + Mid$(Fecha.Text, 4, 2) + Left$(Fecha.Text, 2)
                    !OrdVencimiento = "00000000"
                    !Impre = "AN"
                    .Update
                    .Bookmark = .LastModified
                End If
            End With
        End If
        
        WFecha = Right$(Fecha.Text, 2) + Mid$(Fecha.Text, 4, 2)
        Auxi = Proveedor.Text
        Call Ceros(Auxi, 6)
        
        With rstRetencion
            .Index = "clave"
            Claveven$ = WFecha + Auxi
            .Seek "=", Claveven$
            If .NoMatch = False Then
                .Edit
                !Neto = !Neto + XNeto
                !Retenido = !Retenido + Val(Retencion.Text)
                .Update
            End If
        End With
        
        With rstEmpresa
            .Index = "Empresa"
            .Seek "=", Val(WEmpresa)
            If .NoMatch = False Then
                WAuxiliar = !Nombre
            End If
        End With
    
        With rstAuxiliar
            .Index = "Clave"
            .Seek "=", 1
            If .NoMatch = False Then
                .Edit
                !Nombre = WAuxiliar
                .Update
            End If
        End With
        
        Rem LISTADO.GroupSelectionFormula = "{Pagos.Orden} in " + Chr$(34) + Orden.Text + Chr$(34) + " to " + Chr$(34) + Orden.Text + Chr$(34)
        Rem LISTADO.Destination = 1
        Rem LISTADO.Action = 1
        
        Call IMPREORDEN
        If Val(Retencion.Text) <> 0 Then
            Call Impreret
        End If

        Orden.SetFocus
        Call CmdLimpiar_Click
        
        End If
        
        End If
        
    End If
    End If
End Sub

Private Sub cmdDelete_Click()
    If Orden.Text <> "" Then
                
            Rem Borro los datos anteriores
            
            Rem For iRow = 0 To 20
            Rem     Auxi1 = Str$(iRow)
            Rem     Call Ceros(Auxi1, 2)
            Rem     .Seek "=", Orden.text + Auxi1
            Rem     If .NoMatch = False Then
            Rem         .Delete
            Rem     End If
            Rem Next iRow

    End If
    Proveedor.SetFocus
End Sub

Private Sub CmdLimpiar_Click()
    For iCol = 0 To 12
        For iRow = 0 To 9
            DbGrid1.Col = iCol
            DbGrid1.Row = iRow
            DbGrid1.Text = ""
        Next iRow
    Next iCol
    Orden.Text = ""
    Proveedor.Text = ""
    DesProveedor.Caption = ""
    Observaciones.Text = ""
    Fecha.Text = Mid$(Date$, 4, 2) + "/" + Left$(Date$, 2) + "/" + Right$(Date$, 4)
    Tipo1.Value = True
    Tipo2.Value = False
    Tipo3.Value = False
    Tipo4.Value = False
    Tipo5.Value = False
    Debitos.Caption = ""
    Creditos.Caption = ""
    Banco.Text = ""
    DesBanco.Caption = ""
    Retencion.Text = ""
    Orden.SetFocus
    
    With rstSolicitud
        .Index = "Clave"
        Claveven$ = "99999999"
        .Seek "<=", Claveven$
        If .NoMatch = False Then
            Orden.Text = !Orden + 1
                Else
            Orden.Text = ""
        End If
    End With
    
    Pantalla.Visible = False
    Opcion.Visible = False
    IngreCuenta.Visible = False
    Erase WCuenta
    
End Sub

Private Sub cmdClose_Click()
    Call CmdLimpiar_Click
    With rstEmpresa
        .Close
    End With
    With rstProveedor
        .Close
    End With
    With rstIvaComp
        .Close
    End With
    Rem With rstRecibos
    Rem     .Close
    Rem End With
    With rstSolicitud
        .Close
    End With
    With rstCtaCtePrv
        .Close
    End With
    With rstBanco
        .Close
    End With
    With rstCuenta
        .Close
    End With
    DbsAdminis.Close
    Orden.SetFocus
    Prgpago.Hide
    Unload Me
    Menu.Show
End Sub

Private Sub CmdLimpiar_gotFocus()
    Call CmdLimpiar_Click
End Sub

Private Sub Form_Activate()
    OPEN_FILE_Empresa
    OPEN_FILE_Cuenta
    OPEN_FILE_Proveedor
    OPEN_FILE_CtaCtePrv
    OPEN_FILE_Ivacomp
    OPEN_FILE_Auxiliar
    OPEN_FILE_Banco
    OPEN_FILE_Pagos
    OPEN_FILE_Retencion
    Rem OPEN_FILE_Recibos
End Sub

Private Sub Impresion_Click()
        Call IMPREORDEN
        If Val(Retencion.Text) <> 0 Then
            Call Impreret
        End If
        Rem Listado.GroupSelectionFormula = "{Pagos.Orden} in " + Chr$(34) + Orden.Text + Chr$(34) + " to " + Chr$(34) + Orden.Text + Chr$(34)
        Rem Listado.Destination = 1
        Rem Listado.Action = 1
End Sub


Private Sub Limpia1_Click()
        A = DbGrid1.Row
        B = DbGrid1.Col
        If B <= 5 Then
            DbGrid1.Col = 0
            DbGrid1.Text = ""
            DbGrid1.Col = 1
            DbGrid1.Text = ""
            DbGrid1.Col = 2
            DbGrid1.Text = ""
            DbGrid1.Col = 3
            DbGrid1.Text = ""
            DbGrid1.Col = 4
            DbGrid1.Text = ""
            DbGrid1.Col = 5
            DbGrid1.Text = ""
                Else
            DbGrid1.Col = 6
            DbGrid1.Text = ""
            DbGrid1.Col = 7
            DbGrid1.Text = ""
            DbGrid1.Col = 8
            DbGrid1.Text = ""
            DbGrid1.Col = 9
            DbGrid1.Text = ""
            DbGrid1.Col = 10
            DbGrid1.Text = ""
            DbGrid1.Col = 11
            DbGrid1.Text = ""
        End If
        Call Suma_Datos
End Sub

Private Sub Orden_Keypress(KeyAscii As Integer)
    If KeyAscii = 13 Then
        Auxi1 = Orden.Text
        Call Ceros(Auxi1, 6)
        Orden.Text = Auxi1
        
        With rstSolicitud
            Existe = "N"
            .Index = "Clave"
            Claveven$ = Orden.Text + "01"
            .Seek "=", Claveven$
            If .NoMatch = False Then
                Existe = "S"
                Proveedor.Text = !Proveedor
                Fecha.Text = !Fecha
                Retencion.Text = !Retencion
                Retencion.Text = Pusing("###,###.##", Retencion.Text)
                Tipo1.Value = False
                Tipo2.Value = False
                Tipo3.Value = False
                Tipo4.Value = False
                Tipo5.Value = False
                Select Case Val(!TipoOrd)
                    Case 1
                        Tipo1.Value = True
                    Case 2
                        Tipo2.Value = True
                    Case 3
                        Tipo3.Value = True
                    Case 4
                        Tipo4.Value = True
                    Case 5
                        Tipo5.Value = True
                    Case Else
                End Select
                Observaciones.Text = !Observaciones
                
            End If
        End With
        If Existe = "S" Then
            Call Imprime_Datos
            Call Lee_Datos
            Call Suma_Datos
            DbGrid1.Col = 0
            DbGrid1.Row = 0
            DbGrid1.SetFocus
                Else
            Fecha.SetFocus
        End If
    End If
End Sub

Private Sub Fecha_Keypress(KeyAscii As Integer)
    If KeyAscii = 13 Then
        Call Valida_fecha1(Fecha.Text, Auxi)
        If Auxi = "S" Then
            If Tipo3.Value = True Or Tipo4.Value = True Or Tipo5.Value = True Then
                Observaciones.SetFocus
                    Else
                Proveedor.SetFocus
            End If
                Else
            Fecha.SetFocus
        End If
    End If
End Sub

Private Sub Proveedor_KeyPress(KeyAscii As Integer)
    If KeyAscii = 13 Then
        If Val(Proveedor.Text) <> 0 Then
            With rstProveedor
                .Index = "Proveedor"
                Claveven$ = Proveedor.Text
                .Seek "=", Proveedor.Text
                If .NoMatch Then
                    Proveedor.Text = Claveven$
                    Proveedor.SetFocus
                        Else
                    Proveedor.Text = !Proveedor
                    DesProveedor.Caption = !Nombre
                    WPrvDireccion = !Direccion
                    WPrvCuit = !Cuit
                    WTipoprv = Val(!Tipo) + 1
                    WTipoiva = Val(!Iva)
                    Observaciones.SetFocus
                End If
            End With
        End If
    End If
    Call NumbersOnly(Screen.ActiveControl, KeyAscii)
End Sub

Private Sub Observaciones_Keypress(KeyAscii As Integer)
    If KeyAscii = 13 Then
        If Tipo4.Value = True Then
            Banco.SetFocus
                Else
            DbGrid1.Col = 0
            DbGrid1.Row = 0
            DbGrid1.SetFocus
        End If
    End If
End Sub

Private Sub Banco_KeyPress(KeyAscii As Integer)
    If KeyAscii = 13 Then
        If Val(Banco.Text) <> 0 Then
            With rstBanco
                .Index = "Banco"
                Claveven$ = Val(Banco.Text)
                .Seek "=", Val(Banco.Text)
                If .NoMatch Then
                    Banco.Text = Claveven$
                    Banco.SetFocus
                        Else
                    Banco.Text = !Banco
                    DesBanco.Caption = !Nombre
                    WCtabanco = !Cuenta
                    DbGrid1.Col = 0
                    DbGrid1.Row = 0
                    DbGrid1.SetFocus
                End If
            End With
        End If
    End If
    Call NumbersOnly(Screen.ActiveControl, KeyAscii)
End Sub

Private Sub Consulta_Click()

     Pantalla.Visible = False
    
     XRow = DbGrid1.Row
     XCol = DbGrid1.Col

     Opcion.Clear

     Opcion.AddItem "Proveedores"
     Opcion.AddItem "Cuenta Corrientes"
     Opcion.AddItem "Cheques terceros"
     Rem Opcion.AddItem "Documentos"
     Rem Opcion.AddItem "Cuentas Contables"

     Opcion.Visible = True
     
End Sub

Private Sub Opcion_Click()

    Opcion.Visible = False

    Dim IngresaItem As String

    Pantalla.Clear
    WIndice.Clear

    XIndice = Opcion.ListIndex
    
    Select Case XIndice
        Case 0
            Ayuda.Visible = True
            Ayuda.Text = ""
            With rstProveedor
                .Index = "Nombre"
                .MoveFirst
                Do
                    If .EOF = False Then
                        Auxi$ = Mascara("###########", Str$(!Proveedor))
                        IngresaItem = Auxi$ + " " + !Nombre
                        Pantalla.AddItem IngresaItem
                        IngresaItem = !Proveedor
                        WIndice.AddItem IngresaItem
                        .MoveNext
                            Else
                        Exit Do
                    End If
                Loop
            End With
            
        Case 1
            With rstCtaCtePrv
                .Index = "ClaveImpre"
                Auxi = Proveedor.Text
                .Seek ">", Auxi + Space$(100)
                If .NoMatch = False Then
                Do
                    If .EOF = False Then
                        If Proveedor.Text = !Proveedor Then
                            If !Saldo <> 0 Then
                                Auxi$ = Str$(!Saldo)
                                Auxi$ = Mascara("###,###.##", Auxi$)
                                IngresaItem = !Impre + " " + !Letra + " " + !Punto + " " + !Numero + " " + !Fecha + " " + Auxi$
                                Pantalla.AddItem IngresaItem
                                IngresaItem = !Clave
                                WIndice.AddItem IngresaItem
                            End If
                            .MoveNext
                                Else
                            Exit Do
                        End If
                                Else
                        Exit Do
                    End If
                Loop
                End If
            End With
            
        Case 2
            Rem With rstRecibos
            Rem     .Index = "Fecha2"
            Rem     .MoveFirst
            Rem     Do
            Rem         If .EOF = False Then
            Rem             If Val(!Tiporeg) = 2 Then
            Rem                 If Val(!Tipo2) = 2 And !Estado2 <> "X" Then
            Rem                     Auxi$ = Str$(!Importe2)
            Rem                     Auxi$ = Mascara("###,###.##", Auxi$)
            Rem                     Numero = Str$(Val(!Numero2))
            Rem                     Call Ceros(Numero, 6)
            Rem                     IngresaItem = Numero + "  " + !Fecha2 + "  " + Auxi$ + "  " + !Banco2
            Rem                     Pantalla.AddItem IngresaItem
            Rem                     IngresaItem = !Clave
            Rem                     WIndice.AddItem IngresaItem
            Rem                 End If
            Rem             End If
            Rem             .MoveNext
            Rem                 Else
            Rem             Exit Do
            Rem         End If
            Rem     Loop
            Rem End With
            
        Case 3
            With rstCtaCte
                .Index = "Clave"
                .MoveFirst
                Do
                    If .EOF = False Then
                        If Val(!Tipo) = 50 Then
                            WSaldo = !Saldo
                            Call Redondeo(WSaldo)
                            Rem If !Numero = 5604 Then Stop
                            If WSaldo <> 0 And !Cliente <> Space$(6) Then
                                Auxi$ = Str$(Abs(!Saldo))
                                Auxi$ = Mascara("###,###.##", Auxi$)
                                WNumero = !Numero
                                Call Ceros(WNumero, 6)
                                IngresaItem = WNumero + "  " + !Vencimiento1 + "  " + Auxi$ + "  " + !Cliente
                                Pantalla.AddItem IngresaItem
                                IngresaItem = !Clave
                                WIndice.AddItem IngresaItem
                            End If
                        End If
                        .MoveNext
                            Else
                        Exit Do
                    End If
                Loop
            End With
            
        Case 4
            With rstCuenta
                .Index = "Cuenta"
                .MoveFirst
                Do
                    If .EOF = False Then
                        IngresaItem = !Cuenta + "  " + !Descripcion
                        Pantalla.AddItem IngresaItem
                        IngresaItem = !Cuenta
                        WIndice.AddItem IngresaItem
                        .MoveNext
                            Else
                        Exit Do
                    End If
                Loop
            End With
     
        Case Else
    End Select
            
    Pantalla.Visible = True

End Sub

Private Sub Pantalla_Click()
    Select Case XIndice
        Case 0
            With rstProveedor
                Indice = Pantalla.ListIndex
                Claveven$ = WIndice.List(Indice)
                Proveedor.Text = Claveven$
                .Index = "Proveedor"
                .Seek "=", Claveven$
                If .NoMatch = False Then
                    DesProveedor.Caption = !Nombre
                    WPrvDireccion = !Direccion
                    WPrvCuit = !Cuit
                    WTipoprv = Val(!Tipo) + 1
                    WTipoiva = Val(!Iva)
                            Else
                    Proveedor.Text = ""
                End If
            End With
                
            Ayuda.Visible = False
            Pantalla.Visible = False
            Proveedor.SetFocus
            
        Case 1
        
            If Tipo1.Value = True Then
            
            Entra = "S"
            Indice = Pantalla.ListIndex
            Compara1 = WIndice.List(Indice)
        
            For iRow = 0 To 9
                DbGrid1.Row = iRow
                DbGrid1.Col = 1
                Compara2 = Proveedor.Text + DbGrid1.Text
                DbGrid1.Col = 0
                Compara2 = Compara2 + DbGrid1.Text
                DbGrid1.Col = 2
                Compara2 = Compara2 + DbGrid1.Text
                DbGrid1.Col = 3
                Compara2 = Compara2 + DbGrid1.Text
                If Compara1 = Compara2 Then
                    Entra = "N"
                    Exit For
                End If
            Next iRow
            
            If Entra = "S" Then
            
            For iRow = 0 To 9
                DbGrid1.Row = iRow
                DbGrid1.Col = 0
                If DbGrid1.Text = "" Then
                    XRow = DbGrid1.Row
                    Exit For
                End If
            Next iRow
        
            With rstCtaCtePrv

                Indice = Pantalla.ListIndex
                Claveven$ = WIndice.List(Indice)
                .Index = "CtaCte"
                .Seek "=", Claveven$
                If .NoMatch = False Then
                
                    DbGrid1.Row = XRow
                    DbGrid1.Col = 0
                    DbGrid1.Text = !Tipo
                
                    DbGrid1.Row = XRow
                    DbGrid1.Col = 1
                    DbGrid1.Text = !Letra
                
                    DbGrid1.Row = XRow
                    DbGrid1.Col = 2
                    DbGrid1.Text = !Punto
                
                    DbGrid1.Row = XRow
                    DbGrid1.Col = 3
                    DbGrid1.Text = !Numero
                
                    DbGrid1.Row = XRow
                    DbGrid1.Col = 4
                    DbGrid1.Text = !Saldo
                    DbGrid1.Text = Pusing("###,###.##", DbGrid1.Text)
                    
                    DbGrid1.Row = XRow
                    DbGrid1.Col = 5
                    DbGrid1.Text = "Pago factura nro. " + Str$(!Numero)
                    
                    Call Suma_Datos
                    
                    DbGrid1.Row = XRow
                    DbGrid1.Col = 4
                    
                End If
            End With
            
            End If
            
            End If
                
            DbGrid1.Row = XRow
            DbGrid1.Col = 0
            DbGrid1.SetFocus
            
        Case 2
        
            Entra = "S"
            Indice = Pantalla.ListIndex
            Compara1 = WIndice.List(Indice)
        
            For iRow = 0 To 9
                DbGrid1.Row = iRow
                DbGrid1.Col = 12
                Compara2 = DbGrid1.Text
                If Compara1 = Compara2 Then
                    Entra = "N"
                    Exit For
                End If
            Next iRow
            
            If Entra = "S" Then
            
            For iRow = 0 To 9
                DbGrid1.Row = iRow
                DbGrid1.Col = 6
                If DbGrid1.Text = "" Then
                    XRow = DbGrid1.Row
                    Exit For
                End If
            Next iRow
        
        
            With rstRecibos
                Indice = Pantalla.ListIndex
                Claveven$ = WIndice.List(Indice)
                .Index = "Clave"
                .Seek "=", Claveven$
                If .NoMatch = False Then
                
                    DbGrid1.Col = 6
                    If XIndice = 2 Then
                        DbGrid1.Text = "3"
                            Else
                        DbGrid1.Text = "4"
                    End If
                    
                    DbGrid1.Col = 7
                    DbGrid1.Text = !Numero2
                
                    DbGrid1.Col = 8
                    DbGrid1.Text = !Fecha2
                
                    DbGrid1.Col = 9
                    DbGrid1.Text = ""
                
                    DbGrid1.Col = 10
                    DbGrid1.Text = !Banco2
                
                    DbGrid1.Col = 11
                    DbGrid1.Text = !Importe2
                    DbGrid1.Text = Pusing("###,###.##", DbGrid1.Text)
                    
                    DbGrid1.Col = 12
                    DbGrid1.Text = Claveven$
                    
                    Call Suma_Datos
                    
                    DbGrid1.Row = XRow
                    DbGrid1.Col = 4
                    
                    Pantalla.List(Indice) = ""
                    
                End If
                If DbGrid1.Row < 10 Then
                    DbGrid1.Row = DbGrid1.Row + 1
                    DbGrid1.Col = 6
                    KeyCode = 0
                            Else
                    DbGrid1.Col = 6
                    KeyCode = 0
                End If
            End With
            
            End If
            
        Case 3
        
            Entra = "S"
            Indice = Pantalla.ListIndex
            Compara1 = WIndice.List(Indice)
        
            For iRow = 0 To 9
                DbGrid1.Row = iRow
                DbGrid1.Col = 12
                Compara2 = DbGrid1.Text
                If Compara1 = Compara2 Then
                    Entra = "N"
                    Exit For
                End If
            Next iRow
            
            If Entra = "S" Then
            
            For iRow = 0 To 9
                DbGrid1.Row = iRow
                DbGrid1.Col = 6
                If DbGrid1.Text = "" Then
                    XRow = DbGrid1.Row
                    Exit For
                End If
            Next iRow
        
        
            With rstCtaCte
                Indice = Pantalla.ListIndex
                Claveven$ = WIndice.List(Indice)
                .Index = "Clave"
                .Seek "=", Claveven$
                If .NoMatch = False Then
                
                    DbGrid1.Col = 6
                    DbGrid1.Text = "4"
                    
                    DbGrid1.Col = 7
                    DbGrid1.Text = !Numero
                
                    DbGrid1.Col = 8
                    DbGrid1.Text = !Vencimiento1
                
                    DbGrid1.Col = 9
                    DbGrid1.Text = ""
                
                    DbGrid1.Col = 10
                    DbGrid1.Text = ""
                
                    DbGrid1.Col = 11
                    DbGrid1.Text = !Saldo
                    DbGrid1.Text = Pusing("###,###.##", DbGrid1.Text)
                    
                    DbGrid1.Col = 12
                    DbGrid1.Text = Claveven$
                    
                    Call Suma_Datos
                    
                    DbGrid1.Row = XRow
                    DbGrid1.Col = 4
                    
                    Pantalla.List(Indice) = ""
                    
                End If
                If DbGrid1.Row < 10 Then
                    DbGrid1.Row = DbGrid1.Row + 1
                    DbGrid1.Col = 6
                    KeyCode = 0
                            Else
                    DbGrid1.Col = 6
                    KeyCode = 0
                End If
            End With
            
            End If
            
        Case 4
            With rstCuenta
                Indice = Pantalla.ListIndex
                Claveven$ = WIndice.List(Indice)
                Cuenta.Text = Claveven$
                .Index = "Cuenta"
                .Seek "=", Claveven$
            End With
                
            Pantalla.Visible = False
            Rem Cuenta.SetFocus
                
        Case Else
    End Select
    
End Sub
Private Sub DbGrid1_KeyDown(KeyCode As Integer, Shift As Integer)

    Select Case DbGrid1.Col
    
            Case 0
                If KeyCode = 13 Then
                    If Tipo1.Value = True Then
                        If Val(DbGrid1.Text) = 1 Or Val(DbGrid1.Text) = 2 Or Val(DbGrid1.Text) = 3 Or Val(DbGrid1.Text) = 0 Then
                            Auxi$ = Str$(Val(DbGrid1.Text))
                            Call Ceros(Auxi$, 2)
                            DbGrid1.Text = Auxi$
                            DbGrid1.Col = 4
                            KeyCode = 0
                                Else
                            DbGrid1.Col = 0
                            KeyCode = 0
                        End If
                            Else
                        If Val(DbGrid1.Text) = 0 Then
                            Auxi$ = Str$(Val(DbGrid1.Text))
                            Call Ceros(Auxi$, 2)
                            DbGrid1.Text = Auxi$
                            DbGrid1.Col = 4
                            KeyCode = 0
                                Else
                            DbGrid1.Col = 0
                            KeyCode = 0
                        End If
                    End If
                End If
                
            Case 1
                If KeyCode = 13 Then
                    DbGrid1.Text = Left$(DbGrid1.Text, 1)
                    If Tipo1.Value = True Then
                        If DbGrid1.Text = "A" Or DbGrid1.Text = "C" Or DbGrid1.Text = "X" Then
                            DbGrid1.Col = 2
                            KeyCode = 0
                            Rem no hago anda
                                Else
                            DbGrid1.Col = 1
                            KeyCode = 0
                        End If
                            Else
                        DbGrid1.Col = 2
                        KeyCode = 0
                    End If
                End If
                
            Case 2
                If KeyCode = 13 Then
                    Auxi$ = Str$(Val(DbGrid1.Text))
                    Call Ceros(Auxi$, 4)
                    DbGrid1.Text = Auxi$
                    DbGrid1.Col = 3
                    KeyCode = 0
                End If
                
            Case 3
                If KeyCode = 13 Then
                
                    Auxi$ = Str$(Val(DbGrid1.Text))
                    Call Ceros(Auxi$, 8)
                    DbGrid1.Text = Auxi$
                
                    If Tipo1.Value = True Then
                        With rstCtaCtePrv
                            .Index = "CtaCte"
                            Claveven$ = Proveedor.Text
                            DbGrid1.Col = 1
                            Claveven$ = Claveven$ + DbGrid1.Text
                            DbGrid1.Col = 0
                            Claveven$ = Claveven$ + DbGrid1.Text
                            DbGrid1.Col = 2
                            Claveven$ = Claveven$ + DbGrid1.Text
                            DbGrid1.Col = 3
                            Claveven$ = Claveven$ + DbGrid1.Text
                        
                            .Seek "=", Claveven$
                            If .NoMatch = False Then
                                DbGrid1.Col = 4
                                XRow = DbGrid1.Row
                                If Val(DbGrid1.Text) = 0 Then
                                    DbGrid1.Text = !Saldo
                                    Call Suma_Datos
                                    DbGrid1.Col = 4
                                    DbGrid1.Row = XRow
                                End If
                                DbGrid1.Col = 4
                                KeyCode = 0
                                    Else
                                DbGrid1.Col = 0
                                KeyCode = 0
                            End If
                        End With
                            Else
                        DbGrid1.Col = 4
                        KeyCode = 0
                    End If
                    
                End If
                
            Case 4
                If KeyCode = 13 Then
                
                    If Tipo1.Value = True Then
                        With rstCtaCtePrv
                            .Index = "CtaCte"
                            Claveven$ = Proveedor.Text
                            DbGrid1.Col = 1
                            Claveven$ = Claveven$ + DbGrid1.Text
                            DbGrid1.Col = 0
                            Claveven$ = Claveven$ + DbGrid1.Text
                            DbGrid1.Col = 2
                            Claveven$ = Claveven$ + DbGrid1.Text
                            DbGrid1.Col = 3
                            Claveven$ = Claveven$ + DbGrid1.Text
                            .Seek "=", Claveven$
                            If .NoMatch = False Then
                                Saldo = !Saldo
                                    Else
                                Saldo = 0
                            End If
                        End With
                
                        DbGrid1.Col = 4
                        If Val(DbGrid1.Text) > Saldo Then
                            DbGrid1.Text = ""
                            DbGrid1.Col = 4
                            KeyCode = 0
                                Else
                            DbGrid1.Text = Pusing("###,###.##", DbGrid1.Text)
                            Call Suma_Datos
                            DbGrid1.Col = 5
                            KeyCode = 0
                        End If
                            Else
                        columna = DbGrid1.Row
                        DbGrid1.Text = Pusing("###,###.##", DbGrid1.Text)
                        Call Suma_Datos
                        DbGrid1.Col = 5
                        DbGrid1.Row = columna
                        KeyCode = 0
                    End If
                End If
                
            Case 5
                If KeyCode = 13 Then
                    If Tipo3.Value = True Then
                        Cuenta.Text = WCuenta(DbGrid1.Row)
                        IngreCuenta.Visible = True
                        Cuenta.SetFocus
                    End If
                    If Tipo4.Value = True Then
                        With rstBanco
                            .Index = "Banco"
                            Claveven$ = Val(Banco.Text)
                            .Seek "=", Val(Banco.Text)
                            If .NoMatch = False Then
                                WCuenta(DbGrid1.Row) = !Cuenta
                                    Else
                                WCuenta(DbGrid1.Row) = "999999"
                            End If
                        End With
                    End If
                    If Tipo5.Value = True Then
                        WCuenta(DbGrid1.Row) = "111"
                    End If
                    If DbGrid1.Row < 9 Then
                        DbGrid1.Row = DbGrid1.Row + 1
                        DbGrid1.Col = 0
                        KeyCode = 0
                            Else
                        DbGrid1.Col = 0
                        KeyCode = 0
                    End If
                End If
                
            Case 6
                If KeyCode = 13 Then
                    If Val(DbGrid1.Text) = 1 Or Val(DbGrid1.Text) = 2 Or Val(DbGrid1.Text) = 3 Or Val(DbGrid1.Text) = 4 Then
                        Auxi$ = Str$(Val(DbGrid1.Text))
                        Call Ceros(Auxi$, 2)
                        DbGrid1.Text = Auxi$
                        
                        Select Case Val(DbGrid1.Text)
                        
                            Case 1
                                DbGrid1.Col = 7
                                DbGrid1.Text = ""
                                DbGrid1.Col = 8
                                DbGrid1.Text = ""
                                DbGrid1.Col = 9
                                DbGrid1.Text = ""
                                DbGrid1.Col = 10
                                DbGrid1.Text = "Efectivo"
                                DbGrid1.Col = 11
                                DbGrid1.Columns(11).Locked = False
                                KeyCode = 0
                                
                            Case 3, 4
                                Call Consulta_Click
                                
                            Case Else
                                DbGrid1.Col = 7
                                KeyCode = 0
                                DbGrid1.Columns(7).Locked = False
                                
                        End Select
                        
                            Else
                            
                        DbGrid1.Col = 6
                        KeyCode = 0
                        
                    End If
                End If
                
            Case 7
                If KeyCode = 13 Then
                    DbGrid1.Col = 6
                    If Val(DbGrid1.Text) = 3 Or Val(DbGrid1.Text) = 4 Then
                        DbGrid1.Col = 7
                        KeyCode = 0
                            Else
                        DbGrid1.Col = 7
                        Auxi$ = Str$(Val(DbGrid1.Text))
                        Call Ceros(Auxi$, 8)
                        DbGrid1.Text = Auxi$
                        DbGrid1.Col = 8
                        KeyCode = 0
                        DbGrid1.Columns(7).Locked = True
                        DbGrid1.Columns(8).Locked = False
                    End If
                End If
                
            Case 8
                If KeyCode = 13 Then
                    DbGrid1.Col = 8
                    
                    Call Valida_fecha1(DbGrid1.Text, Auxi)
                    If Auxi <> "S" Then
                        DbGrid1.Col = 8
                        KeyCode = 0
                                Else
                        DbGrid1.Col = 9
                        KeyCode = 0
                        DbGrid1.Columns(8).Locked = True
                        DbGrid1.Columns(9).Locked = False
                    End If
                End If
                
            Case 9
                If KeyCode = 13 Then
                    With rstBanco
                        .Index = "Banco"
                        DbGrid1.Col = 9
                        Claveven$ = DbGrid1.Text
                        .Seek "=", Claveven$
                        If .NoMatch = False Then
                            DbGrid1.Col = 10
                            DbGrid1.Text = !Nombre
                            DbGrid1.Col = 11
                            KeyCode = 0
                            DbGrid1.Columns(9).Locked = True
                            DbGrid1.Columns(11).Locked = False
                                Else
                            DbGrid1.Col = 9
                            KeyCode = 0
                        End If
                    End With
                End If

            Case 11
                
                If KeyCode = 13 Then
                    iRow = DbGrid1.Row
                    DbGrid1.Col = 11
                    DbGrid1.Text = Pusing("###,###.##", DbGrid1.Text)
                    Call Suma_Datos
                    DbGrid1.Row = iRow
                    If DbGrid1.Row < 9 Then
                        DbGrid1.Row = DbGrid1.Row + 1
                        DbGrid1.Col = 6
                        KeyCode = 0
                            Else
                        DbGrid1.Col = 6
                        KeyCode = 0
                    End If
                    DbGrid1.Columns(11).Locked = True
                End If

            Case Else
                
    End Select
    
End Sub
Private Sub DbGrid1_Keypress(KeyAscii As Integer)

    Select Case DbGrid1.Col
            Case 0, 2, 3, 4, 6, 7, 9, 11
                Call NumbersOnly(Screen.ActiveControl, KeyAscii)
            Case Else
                
    End Select
    
End Sub

Private Sub Cuenta_KeyPress(KeyAscii As Integer)
    If KeyAscii = 13 Then
        If Cuenta.Text <> "" Then
            With rstCuenta
                .Index = "Cuenta"
                Claveven$ = Cuenta.Text
                .Seek "=", Cuenta.Text
                If .NoMatch Then
                    Cuenta.SetFocus
                        Else
                    WCuenta(DbGrid1.Row - 1) = Cuenta.Text
                    IngreCuenta.Visible = False
                    Rem DbGrid1.Row = DbGrid1.Row + 1
                    DbGrid1.Col = 0
                    KeyCode = 0
                    DbGrid1.SetFocus
                End If
            End With
        End If
    End If
    Call NumbersOnly(Screen.ActiveControl, KeyAscii)
End Sub

' Cuando el usuario hace clic en el icono Agregar, esta subrutina agrega una
' nueva fila a la variable RowBuf y un marcador a la variable NewRowBookmark
Private Sub DBGrid1_UnboundAddData(ByVal RowBuf As RowBuffer, NewRowBookmark As Variant)
Dim iCol As Integer

mTotalRows = mTotalRows + 1
ReDim Preserve UserData(MAXCOLS - 1, mTotalRows - 1)
NewRowBookmark = mTotalRows - 1 'Establece el marcador a la última fila.

' El bucle siguiente agrega un nuevo registro a la base de datos.
For iCol = 0 To UBound(UserData, 1)
    If Not IsNull(RowBuf.Value(0, iCol)) Then
        UserData(iCol, mTotalRows - 1) = RowBuf.Value(0, iCol)
    Else
        ' Si no se establece ningún valor para la columna, usa DefaultValue
        UserData(iCol, mTotalRows - 1) = DbGrid1.Columns(iCol).DefaultValue
    End If
Next iCol

End Sub

' Esta subrutina elimina una fila basándose en su marcador.
Private Sub DBGrid1_UnboundDeleteRow(Bookmark As Variant)
Dim iCol As Integer, iRow As Integer

' Mueve todas las filas encima de la fila eliminada de
' la matriz.

For iRow = Bookmark + 1 To mTotalRows - 1
    For iCol = 0 To MAXCOLS - 1
        UserData(iCol, iRow - 1) = UserData(iCol, iRow)
    Next iCol
Next iRow
mTotalRows = mTotalRows - 1

End Sub

' Se llama a esta subrutina cada vez que DBGrid quiere mostrar
' datos nuevos.
Private Sub DBGrid1_UnboundReadData(ByVal RowBuf As RowBuffer, StartLocation As Variant, ByVal ReadPriorRows As Boolean)
Dim CurRow&, iRow As Integer, iCol As Integer, iRowsFetched As Integer, iIncr As Integer
' DBGrid está solicitando filas, así que se las damos

If ReadPriorRows Then
    iIncr = -1
Else
    iIncr = 1
End If

' Si StartLocation es Null, empieza a leer por el final
' o por el principio del conjunto de datos.
If IsNull(StartLocation) Then
    If ReadPriorRows Then
        CurRow& = RowBuf.RowCount - 1
    Else
        CurRow& = 0
    End If
Else
    ' Busca la posición para empezar a leer, basándose en el marcador
    ' StartLocation y en la variable iIncr
    CurRow& = CLng(StartLocation) + iIncr
End If

' Transfiere datos de nuestra matriz de conjunto de datos al objeto RowBuf
' que DBGrid utiliza para presentar los datos
For iRow = 0 To RowBuf.RowCount - 1
    If CurRow& < 0 Or CurRow& >= mTotalRows& Then Exit For
    For iCol = 0 To UBound(UserData, 1)
        RowBuf.Value(iRow, iCol) = UserData(iCol, CurRow&)
    Next iCol
    ' Establece el marcador mediante CurRow&, que es también
    ' nuestro índice de matriz
    RowBuf.Bookmark(iRow) = CStr(CurRow&)
    CurRow& = CurRow& + iIncr
    iRowsFetched = iRowsFetched + 1
Next iRow
RowBuf.RowCount = iRowsFetched
End Sub

' Esta subrutina actualiza los datos de la matriz después de
' haberse modificado.

Private Sub DBGrid1_UnboundWriteData(ByVal RowBuf As RowBuffer, WriteLocation As Variant)
Dim iCol As Integer
' Se están actualizando los datos

' Actualiza cada columna de la matriz de conjuntos de datos
For iCol = 0 To MAXCOLS - 1
    If Not IsNull(RowBuf.Value(0, iCol)) Then
        UserData(iCol, WriteLocation) = RowBuf.Value(0, iCol)
    End If
Next iCol

End Sub


Private Sub Form_Load()

ReDim UserData(0 To 12, 0 To 12)

mTotalRows& = 10

Dim oldcnt As Integer, newcnt As Integer

Me.Show
oldcnt = DbGrid1.Columns.Count
newcnt = 0
Dim i As Integer

' Quita las columnas antiguas
For i = DbGrid1.Columns.Count - 1 To 0 Step -1
     DbGrid1.Columns.Remove i
Next i

' Agrega nuevas columnas
For i = 0 To 12
    DbGrid1.Columns.Add newcnt
     Select Case i
         Case 0
             DbGrid1.Columns(newcnt).Caption = "Tipo"
             DbGrid1.Columns(newcnt).Width = 400
             DbGrid1.Columns(newcnt).AllowSizing = False
             DbGrid1.Columns(newcnt).Alignment = 1
             DbGrid1.Columns(newcnt).Locked = True
         Case 1
             DbGrid1.Columns(newcnt).Caption = "Letra"
             DbGrid1.Columns(newcnt).Width = 450
             DbGrid1.Columns(newcnt).AllowSizing = False
             DbGrid1.Columns(newcnt).Locked = True
         Case 2
             DbGrid1.Columns(newcnt).Caption = "Punto"
             DbGrid1.Columns(newcnt).Width = 600
             DbGrid1.Columns(newcnt).AllowSizing = False
             DbGrid1.Columns(newcnt).Alignment = 1
             DbGrid1.Columns(newcnt).Locked = True
         Case 3
             DbGrid1.Columns(newcnt).Caption = "Numero"
             DbGrid1.Columns(newcnt).Width = 1000
             DbGrid1.Columns(newcnt).AllowSizing = False
             DbGrid1.Columns(newcnt).Alignment = 1
             DbGrid1.Columns(newcnt).Locked = True
         Case 4
             DbGrid1.Columns(newcnt).Caption = "Importe"
             DbGrid1.Columns(newcnt).Width = 1200
             DbGrid1.Columns(newcnt).AllowSizing = False
             DbGrid1.Columns(newcnt).Locked = False
             DbGrid1.Columns(newcnt).Alignment = 1
        Case 5
             DbGrid1.Columns(newcnt).Caption = "Descripcion"
             DbGrid1.Columns(newcnt).Width = 2000
             DbGrid1.Columns(newcnt).AllowSizing = False
             DbGrid1.Columns(newcnt).Locked = False
         Case 6
             DbGrid1.Columns(newcnt).Caption = "Tipo"
             DbGrid1.Columns(newcnt).Width = 400
             DbGrid1.Columns(newcnt).AllowSizing = False
             DbGrid1.Columns(newcnt).Locked = False
             DbGrid1.Columns(newcnt).Alignment = 1
         Case 7
             DbGrid1.Columns(newcnt).Caption = "Numero"
             DbGrid1.Columns(newcnt).Width = 1000
             DbGrid1.Columns(newcnt).AllowSizing = False
             DbGrid1.Columns(newcnt).Alignment = 1
             DbGrid1.Columns(newcnt).Locked = True
         Case 8
             DbGrid1.Columns(newcnt).Caption = "Fecha"
             DbGrid1.Columns(newcnt).Width = 1200
             DbGrid1.Columns(newcnt).AllowSizing = False
             DbGrid1.Columns(newcnt).Locked = True
         Case 9
             DbGrid1.Columns(newcnt).Caption = "Banco"
             DbGrid1.Columns(newcnt).Width = 700
             DbGrid1.Columns(newcnt).AllowSizing = False
             DbGrid1.Columns(newcnt).Alignment = 1
             DbGrid1.Columns(newcnt).Locked = True
         Case 10
             DbGrid1.Columns(newcnt).Caption = "Nombre"
             DbGrid1.Columns(newcnt).Width = 1000
             DbGrid1.Columns(newcnt).AllowSizing = False
             DbGrid1.Columns(newcnt).Locked = True
         Case 11
             DbGrid1.Columns(newcnt).Caption = "Importe"
             DbGrid1.Columns(newcnt).Width = 1200
             DbGrid1.Columns(newcnt).AllowSizing = False
             DbGrid1.Columns(newcnt).Alignment = 1
             DbGrid1.Columns(newcnt).Locked = True
         Case 12
             DbGrid1.Columns(newcnt).Caption = ""
             DbGrid1.Columns(newcnt).Width = 10
             DbGrid1.Columns(newcnt).AllowSizing = False
             DbGrid1.Columns(newcnt).Locked = True
        Case Else

     End Select
     DbGrid1.Columns(newcnt).Visible = True
     newcnt = newcnt + 1
 Next i
     
    Tipo1.Value = True
    Tipo2.Value = False
    Tipo3.Value = False
    Tipo4.Value = False
    Tipo5.Value = False
    Orden.Text = ""
    Proveedor.Text = ""
    DesProveedor.Caption = ""
    Fecha.Text = Mid$(Date$, 4, 2) + "/" + Left$(Date$, 2) + "/" + Right$(Date$, 4)
    Tipo1.Value = True
    Tipo2.Value = False
    Tipo3.Value = False
    Tipo4.Value = False
    Tipo5.Value = False
    Debitos.Caption = ""
    Creditos.Caption = ""
    Banco.Text = ""
    DesBanco.Caption = ""
    Retencion.Text = ""
    
    WLeyenda(1) = "Compra de Bienes"
    WLeyenda(2) = "Ejericio Prof. Lib. c/Aj.Inf."
    WLeyenda(3) = "Alquileres y Arrendamientos"
    
    WParametro(0) = 0
    WParametro(1) = 10000
    WParametro(2) = 20000
    WParametro(3) = 40000
    WParametro(4) = 100000
    WParametro(5) = 10000000
    
    WTasa1(1) = 0.1
    WTasa1(2) = 0.135
    WTasa1(3) = 0.17
    WTasa1(4) = 0.205
    WTasa1(5) = 0.24
    
    With rstSolicitud
        .Index = "Clave"
        Claveven$ = "99999999"
        .Seek "<=", Claveven$
        If .NoMatch = False Then
            Orden.Text = !Orden + 1
                Else
            Orden.Text = ""
        End If
    End With
    
End Sub


Private Sub IMPREORDEN()

    Open "lpt1" For Output As #1
    Rem Open "aa" For Output As #1
    
    Print #1, Chr$(27) + Chr$(38) + Chr$(108) + "3" + Chr$(65);
    Print #1, Chr$(27) + Chr$(38) + Chr$(108) + "70" + Chr$(70)
    
        Rem Print #1,Quality = -1

        Rem Printer.Font = "Times New Roman"
        Rem Printer.FontSize = "10"
        Rem Print #1, Tab(1); ""
        Rem Printer.FontSize = "9"

        With rstEmpresa
            .Index = "Empresa"
            Claveven$ = WEmpresa
            .Seek "=", Claveven$
            If .NoMatch = False Then
                Impretit = !Nombre
                    Else
                Impretit = ""
            End If
        End With

        Rem Retenido# = FNRedondeo#(Val(WRetencion.010$)/100)
        Rem Pagado#   = Val(Wpago.010$)/100

        Cantidad = 0
        Total = 0
        SubTotaL = 0
        
        Erase WImpresion, WDebito, WCredito, WImpre2
        
        For iRow = 0 To 10
                WRow = iRow
                DbGrid1.Col = 4
                DbGrid1.Row = iRow
                If Val(DbGrid1.Text) <> 0 Then
                    Cantidad = Cantidad + 1
                    DbGrid1.Col = 0
                    Select Case Val(Left$(DbGrid1.Text, 2))
                        Case 1
                            WImpresion(Cantidad, 2) = "Factura"
                        Case 2
                            WImpresion(Cantidad, 2) = "N.Debito"
                        Case 3
                            WImpresion(Cantidad, 2) = "N.Credito"
                        Case 99
                            WImpresion(Cantidad, 2) = "Varios"
                        Case Else
                            WImpresion(Cantidad, 2) = ""
                    End Select
                            
                    DbGrid1.Col = 3
                    WImpresion(Cantidad, 3) = Left$(DbGrid1.Text, 8)
                    DbGrid1.Col = 5
                    WImpresion(Cantidad, 4) = DbGrid1.Text
                    DbGrid1.Col = 4
                    WImpresion(Cantidad, 5) = DbGrid1.Text
                    If Val(WImpresion(Cantidad, 2)) = 3 Or Val(WImpresion(Cantidad, 2)) = 5 Then
                        Total = Total - Val(WImpresion(Cantidad, 5))
                                                        Else
                        Total = Total + Val(WImpresion(Cantidad, 5))
                    End If
                    
                    DbGrid1.Col = 0
                    WTipo = DbGrid1.Text
                    DbGrid1.Col = 1
                    WLetra = DbGrid1.Text
                    DbGrid1.Col = 2
                    WPunto = DbGrid1.Text
                    DbGrid1.Col = 3
                    WNumero = DbGrid1.Text
                    
                    With rstCtaCtePrv
                        .Index = "CtaCte"
                        Claveven$ = Proveedor.Text + WLetra + WTipo + WPunto + WNumero
                        .Seek "=", Claveven$
                        If .NoMatch = False Then
                            WImpresion(Cantidad, 1) = !Fecha
                                Else
                            WImpresion(Cantidad, 1) = ""
                        End If
                    End With
                    
                End If
        Next iRow
        
        With rstEmpresa
            .Index = "Empresa"
            Claveven$ = "1"
            .Seek "=", Claveven$
            If .NoMatch = False Then
                WCtaProveedor = !CtaProveedores
                WCtaEfectivo = !CtaEfectivo
                WCtaCheques = !CtaCheque
            End If
        End With
        
        If Tipo1.Value = True Or Tipo2.Value = True Then
            WDebito(1, 1) = WCtaProveedor
            WDebito(1, 2) = Total
                Else
            For iRow = 0 To 9
                    WRow = iRow
                    DbGrid1.Col = 4
                    DbGrid1.Row = iRow
                    If Val(DbGrid1.Text) <> 0 Then
                        WDebito(iRow + 1, 1) = WCuenta(iRow)
                        WDebito(iRow + 1, 2) = Val(DbGrid1.Text)
                    End If
            Next iRow
                    
        End If

        WCredito(1, 1) = WCtaProveedor
        If Retenido <> 0 Then
                WCredito(1, 2) = Retenido
        End If
        
        Lugar = 1
        Impre2 = 0
        
        For iRow = 0 To 9
                DbGrid1.Col = 11
                DbGrid1.Row = iRow
                If Val(DbGrid1.Text) <> 0 Then
                    Lugar = Lugar + 1
                    WCredito(Lugar, 4) = DbGrid1.Text
                    DbGrid1.Col = 6
                    Select Case Val(DbGrid1.Text)
                        Case 2
                            WCredito(Lugar, 1) = "999999"
                            With rstBanco
                                DbGrid1.Col = 9
                                .Index = "Banco"
                                .Seek "=", Val(DbGrid1.Text)
                                If .NoMatch = False Then
                                    WCredito(Lugar, 1) = !Cuenta
                                End If
                            End With
                        Case 3, 4
                            WCredito(Lugar, 1) = WCtaCheques
                        Case Else
                            WCredito(Lugar, 1) = WCtaEfectivo
                    End Select
                    
                    Impre2 = Impre2 + 1
                    DbGrid1.Col = 7
                    WImpre2(Impre2, 1) = DbGrid1.Text
                    DbGrid1.Col = 10
                    WImpre2(Impre2, 2) = DbGrid1.Text
                    DbGrid1.Col = 11
                    WImpre2(Impre2, 3) = DbGrid1.Text
                    
                    DbGrid1.Col = 10
                    WCredito(Lugar, 2) = DbGrid1.Text
                    DbGrid1.Col = 7
                    WCredito(Lugar, 3) = DbGrid1.Text
                    DbGrid1.Col = 11
                    WCredito(Lugar, 4) = DbGrid1.Text
                End If
        Next iRow
        
        SubTotaL = Total - Retenido
        TotalDebito = Total
        TotalCredito = Total

        For Ciclo% = 1 To 1

            Print #1, Chr$(27) + Chr$(40) + Chr$(115) + "10" + Chr$(72);
            Print #1, Tab(1); "SOLICITUD DE ORDEN DE PAGO";
            Print #1, Tab(25); Impretit;
            Print #1, Chr$(27) + Chr$(40) + Chr$(115) + "16" + Chr$(72)
            
            Print #1, Tab(1); String$(127, "-")
            
            Print #1, Tab(1); "|";
            Print #1, Tab(10); "Proveedor";
            Print #1, Tab(60); "     Fecha    ";
            Print #1, Tab(115); "Numero";
            Print #1, Tab(127); "|"
            
            Print #1, Tab(1); "|";
            Print #1, Tab(2); "Sres.:"; DesProveedor.Caption;
            Print #1, Tab(63); Fecha.Text;
            Print #1, Tab(115); Orden.Text;
            Print #1, Tab(127); "|"
            
            Print #1, Tab(1); String$(127, "-")
            
            
            
            Print #1, Tab(1); "|";
            Print #1, Tab(14); "|";
            Print #1, Tab(29); "|";
            Print #1, Tab(39); "|";
            Print #1, Tab(76); "|";
            Print #1, Tab(87); "|";
            Print #1, Tab(88); "Valores o Docucmentos Entregados";
            Print #1, Tab(127); "|"
            
            Print #1, Tab(1); "|";
            Print #1, Tab(2); " Fecha";
            Print #1, Tab(14); "|";
            Print #1, Tab(15); "Numero";
            Print #1, Tab(29); "|";
            Print #1, Tab(30); "Comp.";
            Print #1, Tab(39); "|";
            Print #1, Tab(40); "Descripcion ";
            Print #1, Tab(76); "|";
            Print #1, Tab(78); "Importe";
            Print #1, Tab(87); "|";
            Print #1, Tab(88); "Nro.";
            Print #1, Tab(96); "|";
            Print #1, Tab(97); "Banco/Cliente";
            Print #1, Tab(116); "|";
            Print #1, Tab(117); " Importe";
            Print #1, Tab(127); "|"

            Print #1, Tab(1); String$(127, "-")
    
            For WCiclo = 1 To 10

                If Val(WImpresion(WCiclo, 5)) <> 0 Then
                
                    Print #1, Tab(1); "|";
                    Print #1, Tab(2); ""; WImpresion(WCiclo, 1);
                    Print #1, Tab(14); "|";
                    
                    With rstIvaComp
                       .Index = "NroInterno"
                       Claveven$ = Val(WImpresion(WCiclo, 3))
                       .Seek "=", Claveven$
                       If .NoMatch = False Then
                           XImpre = !Numero
                               Else
                           XImpre = WImpresion(WCiclo, 3)
                       End If
                    End With
                    Print #1, Tab(15); ""; XImpre;

                    Rem Print #1, Tab(15); ""; WImpresion(WCiclo, 3);
                    
                    Print #1, Tab(29); "|";
                    Print #1, Tab(30); ""; WImpresion(WCiclo, 2);
                    Print #1, Tab(39); "|";
                    Print #1, Tab(40); ""; WImpresion(WCiclo, 4);
                    Print #1, Tab(76); "|";
                    Print #1, Tab(77); ""; Alinea("###,###.##", WImpresion(WCiclo, 5));
                    Print #1, Tab(87); "|";
                    
                    If Val(WImpre2(WCiclo, 3)) <> 0 Then
                        DbGrid1.Col = 7
                        Print #1, Tab(88); WImpre2(WCiclo, 1);
                        DbGrid1.Col = 10
                        Print #1, Tab(96); "|";
                        Print #1, Tab(97); Left$(WImpre2(WCiclo, 2), 19);
                        DbGrid1.Col = 11
                        Print #1, Tab(116); "|";
                        Print #1, Tab(117); Alinea("###,###.##", WImpre2(WCiclo, 3));
                            Else
                        Print #1, Tab(92); "";
                        Print #1, Tab(96); "|";
                        Print #1, Tab(116); "|";
                    End If
                    Print #1, Tab(127); "|"
                    
                            Else
                            
                    Print #1, Tab(1); "|";
                    Print #1, Tab(14); "|";
                    Print #1, Tab(29); "|";
                    Print #1, Tab(39); "|";
                    Print #1, Tab(76); "|";
                    Print #1, Tab(87); "|";
                    If Val(WImpre2(WCiclo, 3)) <> 0 Then
                        DbGrid1.Col = 7
                        Print #1, Tab(88); WImpre2(WCiclo, 1);
                        DbGrid1.Col = 10
                        Print #1, Tab(96); "|";
                        Print #1, Tab(97); Left$(WImpre2(WCiclo, 2), 19);
                        DbGrid1.Col = 11
                        Print #1, Tab(116); "|";
                        Print #1, Tab(117); Alinea("###,###.##", WImpre2(WCiclo, 3));
                            Else
                        Print #1, Tab(92); "";
                        Print #1, Tab(96); "|";
                        Print #1, Tab(116); "|";
                    End If
                    Print #1, Tab(127); "|"

                End If

            Next WCiclo

            Print #1, Tab(1); String$(127, "-")
            
            Print #1, Tab(1); "|";
            Print #1, Tab(3); " Importe ";
            Print #1, Tab(20); ""; Alinea("###,###.##", Str$(Total));
            Print #1, Tab(40); " Retencion";
            Print #1, Tab(50); ""; Alinea("###,###.##", Retencion.Text);
            Print #1, Tab(80); " Importe neto a Pagar";
            Print #1, Tab(110); ""; Alinea("###,###.##", Str$(Total - Val(Retencion.Text)));
            Print #1, Tab(127); "|"

            Print #1, Tab(1); String$(127, "-")

            Rem Print #1, Tab(1); "     Codigo";
            Rem Print #1, Tab(25); "     Importe";
            Rem Print #1, Tab(50); "  Codigo";
            Rem Print #1, Tab(75); "      Banco";
            Rem Print #1, Tab(115); "  Cheque";
            Rem Print #1, Tab(127); "  Importe";
            Rem Print #1, Tab(150); ""
            Rem
            Rem Print #1, Tab(1); String$(120, "_")
            Rem
            Rem For da = 1 To 10
            Rem         If Val(WDebito$(da, 2)) <> 0 Or Val(WCredito(da, 4)) <> 0 Then
            Rem             Print #1, Tab(1); ""; WDebito(da, 1);
            Rem             Print #1, Tab(25); "";
            Rem             If Val(WDebito(da, 2)) <> 0 Then
            Rem                 Print #1, Tab(30); Alinea("#,###,###.##", WDebito$(da, 2));
            Rem             End If
            Rem             Print #1, Tab(50); ""; WCredito(da, 1);
            Rem             Print #1, Tab(75); ""; WCredito(da, 2);
            Rem             Print #1, Tab(115); ""; WCredito(da, 3);
            Rem             Print #1, Tab(127); "";
            Rem             If Val(WCredito(da, 4)) <> 0 Then
            Rem                 Print #1, Tab(135); Alinea("#,###,###.##", WCredito$(da, 4));
            Rem             End If
            Rem             Print #1, Tab(150); ""
            Rem         End If
            Rem Next da
            Rem
            Rem Print #1, Tab(1); String$(120, "_")
            Rem
            Rem Print #1, Tab(1); " Total Debito";
            Rem Print #1, Tab(30); ""; Alinea("#,###,###.##", Str$(Total));
            Rem Print #1, Tab(50); "";
            Rem Print #1, Tab(75); "";
            Rem Print #1, Tab(115); " Total Credito";
            Rem Print #1, Tab(135); ""; Alinea("#,###,###.##", Str$(Total));
            Rem Print #1, Tab(150); ""
            Rem
            Rem
            Rem Print #1, Tab(1); String$(127, "_")
            
            Print #1, Tab(1); "|";
            Print #1, "OBSERVACIONES :"; Observaciones.Text;
            Print #1, Tab(127); "|"
            
            
            
            Print #1, Tab(1); String$(127, "-")

            Print #1, Tab(1); "|";
            Print #1, Tab(127); "|"
            Print #1, Tab(1); "|";
            Print #1, Tab(127); "|"
            Print #1, Tab(1); "|";
            Print #1, Tab(127); "|"
            
            Print #1, Tab(1); "|";
            Print #1, Tab(10); "   Confecciono";
            Print #1, Tab(35); "    Autorizo";
            Print #1, Tab(60); "   1ra Firma";
            Print #1, Tab(85); "   2da Firma";
            Print #1, Tab(105); "  Recibi Conforme";
            Print #1, Tab(127); "|"
            
            Print #1, Tab(1); String$(127, "-")
            Print #1, ""
            Print #1, ""
            Print #1, ""

  Next Ciclo%
  Print #1, Chr$(12)
  
  Close #1

End Sub


Private Sub Impreret()

    Open "lpt1" For Output As #1

    Print #1, Chr$(15);

    Rem m# = Rete2784#
    
    Mes% = Val(Mid$(Fecha.Text, 3, 2))
    WCuatri = ""

    If Mes% <= 4 Then
        WCuatri = "Primer Cuatrimestre"
            Else
        If Mes% >= 5 And Mes% <= 8 Then
            WCuatri = "Segundo Cuatrimestre"
                Else
            If Mes% >= 9 Then
                WCuatri = "Tercer Cuatrimestre"
            End If
        End If
    End If
    
    WEmpNombre = "ALTRE OPERE S.R.L."
    WEmpDireccion = "CALLAO 1016 8 A"
    WEmpLocalidad = "CAPITAL FEDERAL"
    WEmpCuit = "30-70724870-6"

    Print #1, Chr$(27) + Chr$(40) + Chr$(115) + "16" + Chr$(72)
    
    For da = 1 To 2
        Print #1, ""
        Print #1, "                                                     COMPROBANTE DE RETENCION"
        Print #1, "                                                IMPUESTO A LAS GANACIAS RG 2784                            "
        Print #1, WEmpNombre
        Print #1, WEmpDireccion
        Print #1, WEmpLocalidad
        Print #1, "Clave Unica de Identificacion Tributaria : ", WEmpCuit
        Print #1, "----------------------------------------------------------------------------------------------------------------------------------"
        Print #1, "SUJETO RETENIDO                                                                               |"
        Print #1, "                                                                                              |"
        Print #1, "Nombre/Razon Social : "; DesProveedor.Caption; Tab(95); "|"
        Print #1, "Domicilio           : "; WPrvDireccion; Tab(95); "|"
        Print #1, "Clave Unica de Identificacion Tributaria : "; WPrvCuit; Tab(95); "|"
        Print #1, "..............................................................................................|"
        Print #1, "                                                                                              |"
        Print #1, "DETALLE DE LA RETENCION                                                                       |"
        Print #1, "                                                                                              |"
        Print #1, "Concepto de la Retencion : "; WLeyenda$(Val(WTipoprv)); Tab(95); "|"
        Print #1, "Importe Pagado           : "; Alinea("###,###.##", Str$(Total - WRetencion)); Tab(95); "|"
        Print #1, "Importe Retenido         : "; Alinea("###,###.##", Str$(WRetencion)); Tab(95); "|"
        Print #1, "                                                                                              |----------------------------------"
        Print #1, ".................................................................................................................................."
        Print #1,
        Print #1, "La Presente Retencion efectuada el "; Fecha.Text; " se informara en la Declaracion Jurada del mes."
        Print #1, ""
        Print #1, "=================================================================================================================================="
    Next da
    Print #1, Chr$(12)
    
    Close #1

End Sub


Private Sub calcret_Click()

    WRetencion = 0
    
    If Tipo1.Value = True Or Tipo2.Value = True Then
    
        If WTipoprv = 1 Or WTipoprv = 2 Or WTipoprv = 3 Then
        
            Rem VidPop "Fill Page 1"
            Rem VidPop "Admi540i"
            Rem
            Rem Call Ingreso(Iva$, "N", "", 5, 2, 11, 53, 7, 0, "###.##", A$)
            Rem
            Rem VidPop "Display Page 1"
                    
            Rem If Val(RecordPrv.pago) = 1 Then
            Rem     Concepto$ = "8"
            Rem             Else
            Rem     If Val(RecordPrv.pago) = 2 Then
            Rem             Concepto$ = "13"
            Rem                     Else
            Rem             If Val(RecordPrv.pago) = 3 Then
            Rem                     Concepto$ = "6"
            Rem                             Else
            Rem                     Return
            Rem             End If
            Rem     End If
            Rem End If

            XBruto = Val(Debitos.Caption)
            If TipoIva = 2 Then
                XNeto = (XBruto / 1.21)
                    Else
                XNeto = XBruto
            End If
            XIva = XBruto - XNeto
            XTBase = XNeto
            
            WFecha = Right$(Fecha.Text, 2) + Mid$(Fecha.Text, 4, 2)
            Auxi = Proveedor.Text
            Call Ceros(Auxi, 6)

            With rstRetencion
                .Index = "clave"
                Claveven$ = WFecha + Auxi
                .Seek "=", Claveven$
                If .NoMatch = True Then
                    .AddNew
                    !Fecha = WFecha
                    !Proveedor = Proveedor.Text
                    !Neto = 0
                    !Anticipo = 0
                    !Bruto = 0
                    !Iva = 0
                    !Retenido = 0
                    !Clave = !Fecha + Auxi
                    .Update
                    WNeto = 0
                    WAnticipo = 0
                    WBruto = 0
                    WIva = 0
                    WRetenido = 0
                        Else
                    WNeto = !Neto
                    WAnticipo = !Anticipo
                    WBruto = !Bruto
                    WIva = !Iva
                    WRetenido = !Retenido
                End If
            End With

            If WTipoprv = 1 Then
                WMinimo = 11242.7
                                Else
                If WTipoprv = 2 Then
                        WMinimo = 1124.27
                                        Else
                        WMinimo = 2248.54
                End If
            End If

            WAcupag = WNeto + XTBase
            WAuxi = WAcupag - WMinimo

            If WAuxi <= 0 Then
                WAuxi = 0
                WRetencion = 0
            End If

            WTasa = 0.06
            If WTipoprv = 1 Then
                    WTasa = 0.02
            End If

            Select Case WTipoprv
                Case 2
                    WRetencion = 0
                    WTope = 0
                    WTope1 = 0
                    
                    For da = 0 To 3
                        If WAuxi >= WParametro(da) And WAuxi < WParametro(da + 1) Then
                            WTope1 = WAuxi
                            WTope = WParametro(da)
                            WSum = WTope1 - WTope
                            WSum = WSum * WTasa1(da + 1)
                            WRetencion = WRetencion + WSum
                        End If
                        If WAuxi >= WParametro(da + 1) Then
                            WTope1 = WParametro(da + 1)
                            WTope = WParametro(da)
                            WSum = WTope1 - WTope
                            WSum = WSum * WTasa1(da + 1)
                            WRetencion = WRetencion + WSum
                        End If
                    Next da
                Case Else
                    WRetencion = WAuxi * WTasa
            End Select

            WRetencion = WRetencion - WRetenido

            If WRetencion < 3.75 Then
                WRetencion = 0
                        Else
                If WRetencion > XNeto Then
                        WRetencion = 0
                End If
            End If
                    
            Call Redondeo(WRetencion)
            Retencion.Text = WRetencion
            Retencion.Text = Pusing("###,###.##", Retencion.Text)
            
        End If
        
    End If

End Sub

Private Sub aYUDA_Keypress(KeyAscii As Integer)
    If KeyAscii = 13 Then

    Pantalla.Clear
    WIndice.Clear
    
    WEspacios = Len(Ayuda.Text)
    With rstProveedor
        .Index = "Nombre"
        .MoveFirst
        Do
            If .EOF = False Then
            
                da = Len(!Nombre) - WEspacios
                
                For aa = 1 To da
                    If Left$(Ayuda.Text, WEspacios) = Mid$(!Nombre, aa, WEspacios) Then
                    
                    
                        Auxi = Str$(!Proveedor)
                        Call Ceros(Auxi, 11)
                        IngresaItem = Auxi + "    " + !Nombre
                        Pantalla.AddItem IngresaItem
                        IngresaItem = !Proveedor
                        WIndice.AddItem IngresaItem
                        Exit For
                    End If
                Next aa
                .MoveNext
                    
                        Else
                        
                Exit Do
                
            End If
        Loop
    End With
    
    End If

End Sub



